package com.olima.common.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
  BAD_REQUEST(HttpStatus.BAD_REQUEST),
  VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
  OUTBOUND_REQUEST_REJECTED(HttpStatus.BAD_REQUEST),
  UNSUPPORTED_TOOL_TYPE(HttpStatus.BAD_REQUEST),
  WEAK_PASSWORD(HttpStatus.BAD_REQUEST),

  UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
  INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
  INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
  WIDGET_KEY_REQUIRED(HttpStatus.UNAUTHORIZED),

  FORBIDDEN(HttpStatus.FORBIDDEN),
  INVALID_WIDGET_KEY(HttpStatus.FORBIDDEN),

  NOT_FOUND(HttpStatus.NOT_FOUND),
  ORGANIZATION_NOT_FOUND(HttpStatus.NOT_FOUND),
  TOOL_NOT_FOUND(HttpStatus.NOT_FOUND),
  CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND),
  KNOWLEDGE_BASE_NOT_FOUND(HttpStatus.NOT_FOUND),
  DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
  COMPLAINT_NOT_FOUND(HttpStatus.NOT_FOUND),
  USER_NOT_FOUND(HttpStatus.NOT_FOUND),
  CONNECTION_NOT_FOUND(HttpStatus.NOT_FOUND),

  CONFLICT(HttpStatus.CONFLICT),
  DUPLICATE_USERNAME(HttpStatus.CONFLICT),
  DUPLICATE_NAME(HttpStatus.CONFLICT),
  DUPLICATE_DOCUMENT(HttpStatus.CONFLICT),
  INVALID_STATE(HttpStatus.CONFLICT),
  DATA_INTEGRITY_VIOLATION(HttpStatus.CONFLICT),

  PAYLOAD_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE),
  DOCUMENT_PARSE_FAILED(HttpStatus.UNPROCESSABLE_CONTENT),

  RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
  LOGIN_LOCKED(HttpStatus.TOO_MANY_REQUESTS),
  QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),

  UPSTREAM_ERROR(HttpStatus.BAD_GATEWAY),
  TELEGRAM_API_ERROR(HttpStatus.BAD_GATEWAY),
  INTEGRATION_AUTH_FAILED(HttpStatus.BAD_GATEWAY),
  SERVICE_BUSY(HttpStatus.SERVICE_UNAVAILABLE),

  INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

  private final HttpStatus status;

  ErrorCode(HttpStatus status) {
    this.status = status;
  }

  public HttpStatus status() {
    return status;
  }
}
